### PR TITLE
Fixes an ISE / segfault on some types of certificates

### PR DESCRIPTION
**Pull request by elasticdotventures**

### CODE REVIEW

**Comment by abhishek-ram** [comment]
Why are there so many changes?

**Comment by elasticdotventures** [comment]
I didn't make many changes, I think those changes are mostly yours.   This is the most significant one:

https://github.com/abhishek-ram/pyas2-lib/pull/31/commits/602bdee3d238546cd5894d55ee99649ea9cef53b

**Comment by elasticdotventures** [comment]
I added an error handler & fixed a typo (the rest of the changes are yours)
https://github.com/abhishek-ram/pyas2-lib/pull/31/commits/39214ec3ac58360acaf4a65843a0ab43dde84d54

**Comment by elasticdotventures** [comment]
I think the number of changes is due to moving code across branches?  (they are all your changes) from #31 .. I'm not sure which branch you want commits to.

**Pull request closed without merging**
