### PR TITLE
Fix/brokentests

### LINKED ISSUE #37: Tests do not run - expired certificates
@abhishek-ram : The cert_test.pem/cert_test.p12/cert_test_public.pem have expired in November 2021 and therefore test are failing. Intended to fix this by providing new certificates, however, I was not able to recreate the mecas2 test files that were encrypted with the old certificate. 

Would you be able to update them? Would like to send a pull request for "partnership" callback in relation to: https://github.com/abhishek-ram/django-pyas2/issues/21

### PR DESCRIPTION
**Pull request by chadgates**
https://github.com/abhishek-ram/pyas2-lib/issues/37

Updated certificates (10 years validity) for tests.

Fixed mendelson tests by using public key from mendelson test environment for partner mecas2 to fix #37 and recreated files:

mendelsonAS2_mecas2
mendelsonAS2_pyas2lib

### CODE REVIEW

**Comment by abhishek-ram** [comment]
I guess travis ci is no longer working, should we setup github actions?

**Comment by chadgates** [comment]
I had migrated to travis-ci.com for a quick fix, but github actions would surely be ok as well. 

I followed this: https://oliverde8.medium.com/how-to-migrate-from-travis-ci-org-to-com-5fbcfa541777

**Comment by abhishek-ram** [comment]
> I had migrated to travis-ci.com for a quick fix, but github actions would surely be ok as well.
> 
> I followed this: https://oliverde8.medium.com/how-to-migrate-from-travis-ci-org-to-com-5fbcfa541777

The new service seems to be paid, let me setup actions over the weekend

**Comment by abhishek-ram** [comment]
> I am preparing the branches for the next PRs, but building on top of each other, as decoupling them won't make sense as Black update also made changes to test files. Either way, the build for this PR breaks without the pytest, pylama, black updates, due to package dependencies (typed-ast).

Alright

**Comment by chadgates** [comment]
travis-ci.com should not be a paid service for open source projects: 

Screen Shot 2022-01-07 at 08 35 54

https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by abhishek-ram** [comment]
Merging with master so that I can setup the tests

**Comment by abhishek-ram** [comment]
Actions have been added now...

**Pull request merged**
