### PR TITLE
enforcing CRLF line endings on test data file.

### PR DESCRIPTION
**Pull request by chadgates**
Have enforced CRLF on files by changing the init for the tests. 
Then I run the tests with attached results. 

[Test Results - Nosetests_in_TESTS_.html.zip](https://github.com/abhishek-ram/pyas2-lib/files/3271882/Test.Results.-.Nosetests_in_TESTS_.html.zip)

### CODE REVIEW

**Comment by abhishek-ram** [comment]
all the errors are simply due to the mismatch of input payload and output... where do you see signature errors and don't go with this approach use a separate file called payload_dos.txt with CRLF and use a different test case for it.

**Comment by chadgates** [comment]
[Test Results - Nosetests_in_TESTS_.html.zip](https://github.com/abhishek-ram/pyas2-lib/files/3272009/Test.Results.-.Nosetests_in_TESTS_.html.zip)

better ?

**Comment by chadgates** [comment]
Did some debugging as follows to illustrate the issue, that mic_content is not holding same value as the message and therefore signature or off: 

First, the message is read, the data is data with CRLF line endings. After adding data to the message, the line endings are changed to ”\n"
Step1_ContentData

The message is then added to the multipart Mime with with line endings "\n"
Step2_AddingContentToMime

To create the mic content, canonicalize is called, replacing "\n" with "\r\n", creating a signature that does not match the content that was added in Step 2. 
Step3_CreatingSignatureForContent

**Comment by abhishek-ram** [comment]
Yes but all clients must do canonicalization before verifying signatures, thats why we are not getting any Integrity errors @chadgates

**Comment by abhishek-ram** [comment]
Also @chadgates not sure whats happening but at line 358 `if filename:` the line endings are unchanged. 

image

**Comment by chadgates** [comment]
@abhishek-ram : Can not see _payload in your above print screen. In mine, the line endings are changed. And _payload is what is being used for the BytesGenerator.

**Pull request closed without merging**
