### PR TITLE
Feature/partnership

### PR DESCRIPTION
**Pull request by chadgates**
Adding option to provide a "partnership" callback that accepts org_id and partner_id. 

Updated certificates (10 years validity) for tests. 

Also fixed mendelson tests by using public key from mendelson test environment for partner mecas2 to fix https://github.com/abhishek-ram/pyas2-lib/issues/37 and recreated files:

mendelsonAS2_mecas2
mendelsonAS2_pyas2lib

### CODE REVIEW

**Comment by chadgates** [comment]
Build_Travis

**Comment by abhishek-ram** [comment]
Please move the update of tests certificates and mendelson test fixes to a separate MR

**Comment by abhishek-ram** [comment]
Move the black and pylama changes to MR 2
Move the python 3.10 support to MR 3

**Comment by chadgates** [comment]
Split this up into other branches, thus closing PR.

**Pull request closed without merging**
